### PR TITLE
Feature: Add Current Directory Selection Option

### PR DESCRIPTION
**Pull request by pastacolsugo**
This enhancement introduces the ability to select the current directory (.) when browsing directories in the CLI file selector, improving user experience and navigation efficiency.
Key Improvements:

Provides a straightforward method to select the default path when already in the target directory
Eliminates the previous workaround of navigating up a directory to select the current location
Enables immediate directory validation by allowing selection while viewing directory contents

The implementation adds the ./ option to the directory listing, giving users a more intuitive and direct way to choose their desired path.

### CODE REVIEW

**Comment by br14n-sol** [comment]
Ideally, this option should be shown only when the `type` value is set to `'directory'` or `'file+directory'`.

In the current implementation this option would be present at all times, becoming redundant when you only want to select a file and not a directory.

**Comment by pastacolsugo** [comment]
Updated as requested 🍝

**Review by br14n-sol — APPROVED** [review]

**Comment by br14n-sol** [comment]
Thank you for your contributing 🫡

**Comment by pastacolsugo** [comment]
Thank you for developing it!

Do you have an ETA for the next release? I'm interested in using it directly from `npm`

**Comment by br14n-sol** [comment]
> Thank you for developing it!
> 
> Do you have an ETA for the next release? I'm interested in using it directly from `npm`

Probably during the course of this weekend.

**Comment by br14n-sol** [comment]
Released 👍

**Pull request merged**
