### PR TITLE
Add select directory feature

### PR DESCRIPTION
**Pull request by wenshuishi**
Fix this issue: https://github.com/br14n-sol/inquirer-file-selector/issues/18

### CODE REVIEW

**Comment by br14n-sol** [comment]
Hi, first of all thanks for contributing 👍

I'm not sure about adding it as a default behavior, so far only file selection has been allowed, so it would result in unexpected behavior for anyone using the package from previous versions.

**Comment by br14n-sol** [comment]
I was thinking of adding it along with a configuration option, something like this:

```ts
expected?: 'file' | 'directory' | 'both'
```

Being by default the value of: `'file'`

**Comment by br14n-sol** [comment]
This is just something I thought of just now, if you have a better idea comment it.

**Comment by wenshuishi** [comment]
> Hi, first of all thanks for contributing 👍
> 
> I'm not sure about adding it as a default behavior, so far only file selection has been allowed, so it would result in unexpected behavior for anyone using the package from previous versions.

I think you are right

**Comment by wenshuishi** [comment]
> I was thinking of adding it along with a configuration option, something like this:
> 
> ```ts
> expected?: 'file' | 'directory' | 'both'
> ```
> 
> Being by default the value of: `'file'`

Yes, this way is better.

**Comment by wenshuishi** [comment]
> Hi, first of all thanks for contributing 👍
> 
> I'm not sure about adding it as a default behavior, so far only file selection has been allowed, so it would result in unexpected behavior for anyone using the package from previous versions.

Thanks for reply, yes, you are right, maybe give users an option is better.

**Comment by wenshuishi** [comment]
> I was thinking of adding it along with a configuration option, something like this:
> 
> ```ts
> expected?: 'file' | 'directory' | 'both'
> ```
> 
> Being by default the value of: `'file'`

Ok, i will submit [another pull request](https://github.com/br14n-sol/inquirer-file-selector/pull/20) for that:
 you decide whether to merge it, or you can implement it yourself, if you have any better ideas.

**Pull request closed without merging**
